export const KEY_SYMBOLS: Record<string, { symbol: string; label: string }> = {
    fn: { symbol: "fn", label: "🌐" },
    control: { symbol: "^", label: "control" },
    ctrl: { symbol: "^", label: "control" },
    command: { symbol: "⌘", label: "command" },
    cmd: { symbol: "⌘", label: "command" },
    option: { symbol: "⌥", label: "option" },
    alt: { symbol: "⌥", label: "option" },
    shift: { symbol: "⇧", label: "shift" },
    caps: { symbol: "⇪", label: "caps" },
    capslock: { symbol: "⇪", label: "caps lock" },
    tab: { symbol: "⇥", label: "tab" },
    escape: { symbol: "⎋", label: "esc" },
    esc: { symbol: "⎋", label: "esc" },
    return: { symbol: "↩", label: "return" },
    enter: { symbol: "↩", label: "enter" },
    delete: { symbol: "⌫", label: "delete" },
    backspace: { symbol: "⌫", label: "delete" },
    space: { symbol: "␣", label: "space" },
};
